Add frames from figma
ibrahimspd/pa1469 pull request #16
Opened 2022-12-04 20:21 UTC by Pontusg45

Add Team Info page
Add Generate Linup connection
Add Navigation Bar
Add color picker

2022-12-04 20:52 UTC, ibrahimspd requested changes
.vscode filen ska inte vara där. Såg att du la till den i gitignore, men den verkar inte funka.

Fixat

2022-12-04 20:59 UTC, ibrahimspd commented on app/src/main/java/com/example/myapplication/Controller/TeamInfo.java
> +        Gson gson = new Gson();
Create a static final version of this object incase of reuse.

2022-12-04 21:01 UTC, ibrahimspd reviewed
comment in code.

2022-12-06 13:56 UTC, Pontusg45 reviewed
Fixed

2022-12-06 13:58 UTC, PoloMalone approved these changes
nice

2022-12-06 14:00 UTC, Pontusg45 reviewed
done

2022-12-06 14:00 UTC, Pontusg45 reviewed
done

2022-12-06 14:01 UTC, PoloMalone approved these changes

2022-12-06 14:01 UTC, RobinHellgren01 approved these changes

2022-12-06 14:02 UTC, merged